#!/bin/sh

SCRIPT=/home/neoserv
USER=$(whoami)

if [ "$USER" != "root" ]; then
  echo "Please run as root!"
  exit 0
fi

start() {
  pids=$(pgrep -u neoserv nginx | wc -l)
  if [ $pids != 0 ]; then
    echo 'NeoServ is already running'
    return 1
  fi
  echo 'Starting NeoServ...'
  sudo chown -R neoserv:neoserv /sys/class/net
  sudo chown -R neoserv:neoserv /home/neoserv/content/streams
  sudo chown -R neoserv:neoserv /home/neoserv/tmp
  if [ -f $SCRIPT/bin/redis/redis-server ]; then
    sudo -u neoserv $SCRIPT/bin/redis/redis-server $SCRIPT/bin/redis/redis.conf >/dev/null 2>/dev/null
  fi
  sudo -u neoserv $SCRIPT/bin/nginx/sbin/nginx >/dev/null 2>/dev/null
  sudo -u neoserv $SCRIPT/bin/nginx_rtmp/sbin/nginx_rtmp >/dev/null 2>/dev/null
  sudo -u neoserv $SCRIPT/bin/daemons.sh
  sudo $SCRIPT/bin/php/bin/php $SCRIPT/includes/cli/startup.php
  sudo -u neoserv $SCRIPT/bin/php/bin/php $SCRIPT/includes/cli/signals.php >/dev/null 2>/dev/null &
  sudo -u neoserv $SCRIPT/bin/php/bin/php $SCRIPT/includes/cli/watchdog.php >/dev/null 2>/dev/null &
  sudo -u neoserv $SCRIPT/bin/php/bin/php $SCRIPT/includes/cli/queue.php >/dev/null 2>/dev/null &
  if [ -f $SCRIPT/includes/cli/cache_handler.php ]; then
    sudo -u neoserv $SCRIPT/bin/php/bin/php $SCRIPT/includes/cli/cache_handler.php >/dev/null 2>/dev/null &
  fi
  if [ -f $SCRIPT/includes/cli/connection_sync.php ]; then
    sudo -u neoserv $SCRIPT/bin/php/bin/php $SCRIPT/includes/cli/connection_sync.php >/dev/null 2>/dev/null &
  fi
  echo 'Running in foreground...'
  sleep infinity
}

stop() {
  pids=$(pgrep -u neoserv nginx | wc -l)
  if [ $pids = 0 ]; then
    echo 'NeoServ is not running'
    return 1
  fi
  echo 'Stopping NeoServ...'
  sudo killall -u neoserv
  sleep 1
  sudo killall -u neoserv
  sleep 1
  sudo killall -u neoserv
}

restart() {
  ps -U neoserv | egrep -v "ffmpeg|PID" | awk '{print $1}' | xargs kill -9
  start
}

reload() {
  pids=$(pgrep -u neoserv nginx | wc -l)
  if [ $pids = 0 ]; then
    echo 'NeoServ is not running'
    return 1
  fi
  echo 'Reloading NeoServ...'
  sudo -u neoserv $SCRIPT/bin/nginx/sbin/nginx -s reload
  sudo -u neoserv $SCRIPT/bin/nginx_rtmp/sbin/nginx_rtmp -s reload
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  reload)
    reload
    ;;
  restart)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}"
esac

exit 0
